### ISSUE TITLE
Query builder: Save queries in a collection

### ISSUE THREAD

**Issue by bboure** [graphboltdev/graphbolt#8]
As a user, I want to save queries in a collection to access them easily and quickly. 
I want to be able to execute them.

Same as Postman or Insomnia

**Comment by pgrzesik** [comment]
Big 👍 to this. I was just testing out a few queries and while they're persisted in the query builder, it would be nice to create Postman-like collections for easy access and management.

**Comment by bboure** [comment]
FYI, in the meantime, the workaround you can create several named operations. When clicking `Send` (Cmd+Enter) Graphbolt will ask you which one to execute.

<img width="1508" alt="Screenshot 2022-12-01 at 15 06 10" src="https://user-images.githubusercontent.com/7089997/205073260-c9579d1e-6876-4a8b-b32f-838d53b94c6f.png">

**Comment by pgrzesik** [comment]
That's funny because that was one of the first things that I've tried out 😄 It's a good "workaround" for now for sure 👍

**Comment by bboure** [comment]
Released in v0.3.0
